package model

var InvalidExtensions = map[string]bool{
	".bin":    false,
	".exe":    false,
	".dll":    false,
	".iso":    false,
	".lnk":    false,
	".mp3":    false,
	".mp4":    false,
	".zip":    false,
	".ttf":    false,
	".otf":    false,
	".png":    false,
	".jpg":    false,
	".jpeg":   false,
	".gif":    false,
	".otb":    false,
	".cff":    false,
	".ttc":    false,
	".base64": false,
	".syso":   false,
	".pdf":    false,
	".ppt":    false,
	".doc":    false,
	".docx":   false,
	".pptx":   false,
	".xlsx":   false,
	".xls":    false,
}
